admin:
  port: 9990

namers:
- kind: io.l5d.fs
  rootDir: disco

routers:
- protocol: http
  dtab: |
    /svc => /#/io.l5d.fs;
  httpAccessLog: logs/access.log
  label: int
  servers:
  - port: 4140
    ip: 0.0.0.0
    
- protocol: h2
  label: grpc
  client:
    loadBalancer:
      kind: roundRobin
  dtab: |
    /svc => /#/io.l5d.fs;
  servers:
  - port: 4141
    ip: 0.0.0.0
  identifier:
    kind: io.l5d.header.path
    segments: 1
  
